---
- name: install and launch Metricbeat on Web-Vm's
  hosts: webservers
  become: yes
  tasks:
  - name: Download deb file
    command:
      cmd: curl -L -O "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.d$  - name: install deb file
    command:
      cmd: dpkg -i metricbeat-7.4.0-amd64.deb
  - name: copy Metricbeat config to web-vm
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
  - name: metricbeat modules enable docker command
    command:
      cmd: metricbeat modules enable docker
  - name: metricbeat setup command
    command:
      cmd: metricbeat setup
  - name: metric beat -e
    command:
      cmd: service metricbeat start
  - name: enable metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes